### PR TITLE
Publish feature matrix

### PR DESCRIPTION
**Pull request by mayurkale22**
Visuals

screen shot 2019-02-01 at 12 18 20 pm

### CODE REVIEW

**Comment by mayurkale22** [comment]
/cc @shahprit @odeke-em @songy23 @hvent90 @jparsana 

Many thanks to @hvent90 for helping me out to put this toghther.

**Comment by jparsana** [comment]
@mayurkale22 Nice work!

**Comment by odeke-em** [comment]
Kindly paging @hvent90 to give his LGTM as I don't have UI expertise

**Comment by hvent90** [comment]
LGTM, thanks @mayurkale22!

**Pull request merged**
