### PR TITLE
Update the build instructions for quick start

### PR DESCRIPTION
**Pull request by songy23**
Follow up with my comments in https://github.com/census-instrumentation/opencensus-website/pull/32.

### CODE REVIEW

**Comment by g-easy** [comment]
CLA: I confirm.

**Comment by songy23** [comment]
No worries - but sorry it seems there's some problem with my CLA :( Could you copy the changes and post another PR?

**Comment by songy23** [comment]
> CLAs are signed, but unable to verify author consent

This seems to be because this PR has commits from different persons, and CLA doesn't allow that. I'll post a new PR to update.

**Comment by g-easy** [comment]
Sorry for the trouble. This is the second time I've been bitten by this.

**Pull request closed without merging**
