### PR TITLE
Fix addAnotation in java

### PR DESCRIPTION
**Pull request by bdelbosc**
Annotation.fromDescription does not take attribute, it must be fromDescriptionAndAttributes.

### CODE REVIEW

**Comment by bdelbosc** [comment]
cla: I signed it!

**Comment by odeke-em** [comment]
Hello there @bdelbosc, thank you for the PR and welcome to the OpenCensus project!

So unfortunately I don't think that your update compiles.
As per https://static.javadoc.io/io.opencensus/opencensus-api/0.19.1/io/opencensus/trace/Annotation.html
screen shot 2019-02-05 at 8 38 45 am
 
`fromDescriptionAndAttributes` would also require a map but inside that code `fromDescription` only takes a string which is what we are doing, unless am mistaken.

/cc @songy23 @mayurkale22

**Comment by songy23** [comment]
The original code is
```java
span.addAnnotation(Annotation.fromDescription("Cache miss during GC", map));
```
which is wrong. Correct ones should be either
```java
span.addAnnotation(Annotation.fromDescriptionAndAttributes("Cache miss during GC", map));
```
or
 ```java
span.addAnnotation(Annotation.fromDescription("Cache miss during GC"));
```
Given that `map` is already initialized and used, I think the former makes more sense, which is what this PR proposes.

**Comment by odeke-em** [comment]
Oh, never mind, clearly I was the one who didn't read, my apologies y'all, thank you @bdelbosc and @songy23!

**Pull request merged**
