### PR TITLE
content/community/talks: added more talks

### PR DESCRIPTION
**Pull request by odeke-em**
Update #448

#### Before
screen shot 2018-11-17 at 8 18 33 am

#### After
screen shot 2018-11-17 at 8 18 16 am

### CODE REVIEW

**Comment by hvent90** [comment]
In content.css, replace this:

```cs
.user-card-container.talks p {
    font-size: 14px;
}
```

with this:

```cs
.user-card-container.talks p {
    font-size: 12px;
    height: 44px;
}
```

screen shot 2018-11-17 at 9 32 30 am

**Comment by odeke-em** [comment]
Thanks for the review @songy23!

>Images exceed the height of certain cards. I'll provide a CSS snippet in a comment in a few minutes to fix this

Thanks for the review and update @hvent90! Let me update that as per your prescription.

**Comment by odeke-em** [comment]
And updated, looks a lot better, thanks @hvent90!

**Pull request merged**
