### PR TITLE
Fix the description of RECEIVED message type

### PR DESCRIPTION
**Pull request by pingyeh**

### CODE REVIEW

**Comment by odeke-em** [comment]
Please sign the CLA then comment back here @pingyeh.

**Comment by pingyeh** [comment]
I'm using my @google.com address on github and the CLA page shows that I'm good, but somehow it still flags me as needing to sign CLA. I created the fix and PR all on github.com instead in my Linux command line. Maybe it did not use my @google.com address in the commit. I'm trying to figure this out.

**Comment by odeke-em** [comment]
You make the amendment via the terminal with git as per 
```shell
git commit --amend --author="<Author Name> <email@address.com>"
```

**Comment by odeke-em** [comment]
> I created the fix and PR all on github.com instead in my Linux command line. Maybe it did not use my @google.com address in the commit. I'm trying to figure this out.

And yes creating the commit on Github used a noreply@github* email instead of your proper email.

**Comment by odeke-em** [comment]
Cool, thanks again @pingyeh, LGTM!

**Pull request merged**
