### PR TITLE
fixing typo "pyton" => "python"

### PR DESCRIPTION
**Pull request by SonjaChevre**
"pyton" => "python"

### CODE REVIEW

**Comment by SonjaChevre** [comment]
I have just signed the CLA.

**Comment by songy23** [comment]
Ping @googlebot

**Comment by odeke-em** [comment]
@SonjaChevre unfortunately it doesn't seem to find your CLA associated with this address. Could you please verify? Apologies for this kind of blocker.

**Comment by SonjaChevre** [comment]
@odeke-em the commit was with my work e-mail address. I have signed the CLA with the private e-mail address. I have re-done the pull request here: https://github.com/census-instrumentation/opencensus-website/pull/500

**Pull request closed without merging**
