### PR TITLE
guides/exporters fix : change PrometheusStatsExporter -> PrometheusSt…

### PR DESCRIPTION
**Pull request by mayurkale22**
…atsCollector

### CODE REVIEW

**Comment by odeke-em** [comment]
Thanks @mayurkale22 for the PR, but I am a little confused about this change. It worked before, what's the new change for?

**Comment by songy23** [comment]
@odeke-em is about a typo in the class name - in Java there's a "[PrometheusStatsCollector](https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java)", rather than "PrometheusStatsExporter".

**Comment by mayurkale22** [comment]
@odeke-em I don't know how it used to work before, now I see typo for class name PrometheusStatsCollector.

**Comment by odeke-em** [comment]
Interesting #ghostInTheMachine thank you for the fix!

**Pull request merged**
