### PR TITLE
quickstarts: add C++ metrics

### PR DESCRIPTION
**Pull request by odeke-em**
Added a full quickstart tutorial for C++
metrics with the Prometheus exporter.

Updates #287
Updates #343

### CODE REVIEW

**Comment by g-easy** [comment]
Is there a way to see what this looks like rendered?

**Comment by g-easy** [comment]
Is there a way to see what this looks like rendered?

**Comment by odeke-em** [comment]
@g-easy in regards to
>Is there a way to see what this looks like rendered?

I provided you with a URL of a tunnelled and rendered website offline :)

Thank you @helly25 and @songy23 for the review! @g-easy am going to merge this for now to get it off my plate but also to ensure that you can view it rendered on the website. Please feel free to send corrections and updates.

**Comment by g-easy** [comment]
I'm sorry I ran out of time for this yesterday. I'm reviewing the live version now.

**Comment by odeke-em** [comment]
Not a problem @g-easy, thanks for taking a look at it!

**Pull request merged**
