### PR TITLE
Modify the directory structure

### PR DESCRIPTION
**Pull request by hbgxsm95**

### CODE REVIEW

**Comment by hbgxsm95** [comment]
Already ran the `hugo` to test it. Thanks! @odeke-em

**Comment by songy23** [comment]
"content/blog" -> "content/blogs"

**Comment by odeke-em** [comment]
After @songy23's suggestion of `content/blog` to `content/blogs`, perhaps too make the file `blog.md` into `content/blogs/iot.md` LGTM otherwise.

**Comment by hbgxsm95** [comment]
oh sorry I forget that ! Thanks ! @odeke-em

**Comment by odeke-em** [comment]
Perfect, thanks @hbgxsm95!

**Pull request merged**
