### PR TITLE
Stackdriver rebrand

### PR DESCRIPTION
**Pull request by mtwo**
Changed Stackdriver to Google Cloud Monitoring + Trace

### CODE REVIEW

**Comment by odeke-em** [comment]
You might need to run grep on the whole repository `grep -Ri stackdriver` and then send all the patches at once :)

**Comment by mtwo** [comment]
I’m content to leave the remaining names as the package and API names won’t be changing in OpenCensus, and because people will start moving to OpenTelemetry later this month.

However I will update the compatibility matrix. Doing that now in this PR.

**Comment by mtwo** [comment]
@odeke-em done!

**Comment by odeke-em** [comment]
Awesome, congrats and LGTM!

**Comment by mtwo** [comment]
Thanks!

**Pull request merged**
